# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    update_project_team
    update_code_signing_settings(
          code_sign_identity: "iPhone Distribution",
          profile_name: "match AppStore com.fleetmap.moviflotte"
        )
    set_build_number_repository
    build_app
    api_key = app_store_connect_api_key(
          key_id: "YM99GZAN52",
          issuer_id: "1b6339f6-d9c6-4f41-bf6e-5081d9bd7085",
          duration: 1200)
    upload_to_testflight(skip_waiting_for_build_processing: true, api_key: api_key)
  end
end
